# Generated by Django 4.2.3 on 2023-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_myuser_mapped_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mapped_apis',
            field=models.ManyToManyField(related_name='mapped_users', to='myapp.api'),
        ),
    ]
