# Generated by Django 4.2.3 on 2023-07-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_api_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='mapped_apis',
        ),
    ]
