# Generated by Django 4.2.3 on 2023-07-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_myuser_mapped_apis'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mapped_apis',
            field=models.ManyToManyField(to='myapp.api'),
        ),
    ]
