# Generated by Django 4.2.3 on 2023-07-31 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_myuser_mapped_apis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='mapped_apis',
        ),
    ]
