# Generated by Django 4.2.3 on 2023-07-31 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_api_created_by_myuser_mapped_apis'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='mapped_users',
            field=models.ManyToManyField(related_name='user_mapped_apis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mapped_apis',
            field=models.ManyToManyField(related_name='api_mapped_users', to='myapp.api'),
        ),
    ]
